# Generated by Django 5.2.16 on 2026-07-22 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_participant_age_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('account', 'Account'), ('submission', 'Submission'), ('event', 'Event')], default='account', max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=300)),
                ('destination', models.CharField(blank=True, help_text='Optional local path opened when the notification is selected.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
