# Generated by Django 5.2.16 on 2026-07-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='participant_avatars/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='avatar_moderation_note',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='avatar_review_path',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='avatar_status',
            field=models.CharField(choices=[('none', 'No avatar'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='participant',
            name='avatar_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
