# Generated by Django 5.2.16 on 2026-07-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_participant_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='avatar_status',
            field=models.CharField(choices=[('none', 'No avatar'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Declined')], default='none', max_length=16),
        ),
    ]
