# Generated by Django 5.2.16 on 2026-07-23 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_participant_avatar_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('under_review', 'Under review'), ('approved', 'Approved'), ('declined', 'Declined')], default='under_review', max_length=20)),
                ('export_format', models.PositiveSmallIntegerField()),
                ('generated_at', models.DateTimeField()),
                ('current_kills', models.PositiveBigIntegerField(default=0)),
                ('event_sequence', models.PositiveBigIntegerField(default=0)),
                ('event_hash', models.CharField(max_length=64)),
                ('character_name', models.CharField(blank=True, max_length=160)),
                ('bootstrapped', models.BooleanField(default=False)),
                ('latest_events', models.JSONField(blank=True, default=list)),
                ('first_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='RunSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('approved', 'Approved'), ('declined', 'Declined'), ('superseded', 'Superseded')], default='received', max_length=16)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('raw_export', models.TextField()),
                ('export_format', models.PositiveSmallIntegerField()),
                ('generated_at', models.DateTimeField()),
                ('current_kills', models.PositiveBigIntegerField(default=0)),
                ('event_sequence', models.PositiveBigIntegerField(default=0)),
                ('event_hash', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='registry.challengerun')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
