# Generated by Django 5.2.16 on 2026-07-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_challengerun_runsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengerun',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
    ]
