# Generated by Django 5.2.16 on 2026-07-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_streamingaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengerun',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('deceased', 'Deceased'), ('abandoned', 'Abandoned'), ('completed', 'Completed'), ('invalidated', 'Invalidated')], default='active', max_length=16),
        ),
    ]
