# Generated by Django 5.2.16 on 2026-07-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_challengerun_lifecycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingaccount',
            name='encrypted_access_token',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='streamingaccount',
            name='encrypted_refresh_token',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='streamingaccount',
            name='token_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
