# Generated by Django 5.2.16 on 2026-07-24 02:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_streamingaccount_encrypted_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_clips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_end_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_media_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_media_type',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_provider',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_start_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='StreamingMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('clip', 'Clip')], max_length=12)),
                ('provider_media_id', models.CharField(max_length=255)),
                ('parent_media_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('vod_offset_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='registry.streamingaccount')),
            ],
            options={
                'ordering': ('-published_at', 'kind', 'provider_media_id'),
                'constraints': [models.UniqueConstraint(fields=('account', 'kind', 'provider_media_id'), name='unique_streaming_media_per_account')],
            },
        ),
    ]
