# Generated by Django 5.2.16 on 2026-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_runsubmission_evidence_clips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengerun',
            name='latest_projection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='projection',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
