# Generated by Django 5.2.16 on 2026-07-24 12:22

import django.db.models.deletion
from django.db import migrations, models


def establish_approved_snapshots(apps, schema_editor):
    ChallengeRun = apps.get_model("registry", "ChallengeRun")
    RunSubmission = apps.get_model("registry", "RunSubmission")
    RunSubmission.objects.filter(status="superseded").update(status="received")
    for run in ChallengeRun.objects.all():
        approved = (
            RunSubmission.objects.filter(run=run, status="approved")
            .order_by("-reviewed_at", "-submitted_at")
            .first()
        )
        if not approved:
            run.status = "pending"
            run.save(update_fields=("status",))
            continue
        character = approved.projection.get("character", {})
        snapshot = character.get("current") or character.get("starting") or {}
        name = snapshot.get("displayName") or " ".join(
            value
            for value in (
                str(snapshot.get("forename") or "").strip(),
                str(snapshot.get("surname") or "").strip(),
            )
            if value
        )
        run.status = "official"
        run.approved_submission = approved
        run.export_format = approved.export_format
        run.generated_at = approved.generated_at
        run.current_kills = approved.current_kills
        run.event_sequence = approved.event_sequence
        run.event_hash = approved.event_hash
        run.character_name = name
        run.latest_projection = approved.projection
        run.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_challengerun_latest_projection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengerun',
            name='approved_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.runsubmission'),
        ),
        migrations.RunPython(establish_approved_snapshots, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='challengerun',
            name='review_reason',
        ),
        migrations.RemoveField(
            model_name='challengerun',
            name='reviewed_at',
        ),
        migrations.AlterField(
            model_name='challengerun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending first approval'), ('official', 'Official')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='runsubmission',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('approved', 'Approved'), ('declined', 'Declined')], default='received', max_length=16),
        ),
    ]
