# Generated by Django 5.2.16 on 2026-07-24 21:51

import django.db.models.deletion
from django.db import migrations, models


def link_comparison_baselines(apps, schema_editor):
    RunSubmission = apps.get_model("registry", "RunSubmission")
    for submission in RunSubmission.objects.order_by("run_id", "submitted_at"):
        baseline = (
            RunSubmission.objects.filter(
                run_id=submission.run_id,
                status="approved",
                reviewed_at__lte=submission.submitted_at,
            )
            .exclude(pk=submission.pk)
            .order_by("-reviewed_at", "-submitted_at")
            .first()
        )
        if baseline:
            submission.baseline_submission = baseline
            submission.save(update_fields=("baseline_submission",))


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_remove_challengerun_review_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsubmission',
            name='baseline_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_submissions', to='registry.runsubmission'),
        ),
        migrations.RunPython(link_comparison_baselines, migrations.RunPython.noop),
    ]
