# Generated by Django 5.2.16 on 2026-07-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_runsubmission_baseline_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingaccount',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='streamingaccount',
            name='provider',
            field=models.CharField(choices=[('discord', 'Discord'), ('twitch', 'Twitch'), ('youtube', 'YouTube')], max_length=16),
        ),
    ]
