# Generated by Django 5.2.16 on 2026-07-25 00:48

from django.db import migrations, models


def remove_disconnected_accounts(apps, schema_editor):
    StreamingAccount = apps.get_model("registry", "StreamingAccount")
    StreamingAccount.objects.filter(status="disconnected").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_streamingaccount_provider_metadata_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_disconnected_accounts,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='streamingaccount',
            name='disconnected_at',
        ),
        migrations.AlterField(
            model_name='streamingaccount',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('reconnect_required', 'Reconnect required')], default='connected', max_length=24),
        ),
    ]
