# Generated by Django 5.2.16 on 2026-07-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_remove_disconnected_connection_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamingaccount',
            options={'ordering': ('provider',), 'verbose_name': 'platform integration', 'verbose_name_plural': 'platform integrations'},
        ),
        migrations.AlterModelOptions(
            name='streamingmedia',
            options={'ordering': ('-published_at', 'kind', 'provider_media_id'), 'verbose_name': 'cached streaming media', 'verbose_name_plural': 'cached streaming media'},
        ),
    ]
