# Generated by Django 5.2.16 on 2026-07-25 17:46

import django.db.models.deletion
from django.db import migrations, models


def seed_challenge_modes(apps, schema_editor):
    ChallengeMode = apps.get_model("registry", "ChallengeMode")
    modes = (
        ("TGSRR", "TGSRR - Standard", "The Great Spiffo's Rat Race"),
        ("TGSRR_CDDA", "TGSRR - CDDA", "The Great Spiffo's Rat Race - CDDA"),
        (
            "TGSRR_Sprinters",
            "TGSRR - Sprinters",
            "The Great Spiffo's Rat Race - Sprinters",
        ),
    )
    for display_order, (key, display_name, game_mode_name) in enumerate(modes):
        ChallengeMode.objects.update_or_create(
            key=key,
            defaults={
                "display_name": display_name,
                "game_mode_name": game_mode_name,
                "display_order": display_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_rename_platform_integration_admin_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The exact challenge ID exported by Project Zomboid.', max_length=160, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('game_mode_name', models.CharField(blank=True, help_text='The expected Project Zomboid game-mode name, retained for comparison.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'challenge mode',
                'verbose_name_plural': 'challenge modes',
                'ordering': ('display_order', 'display_name', 'key'),
            },
        ),
        migrations.RunPython(seed_challenge_modes, migrations.RunPython.noop),
        migrations.AddField(
            model_name='challengerun',
            name='challenge_game_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='challengerun',
            name='challenge_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='challenge_game_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='challenge_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='challengerun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending first approval'), ('official', 'Verified')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='challengerun',
            name='challenge_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='registry.challengemode'),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='challenge_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='registry.challengemode'),
        ),
        migrations.CreateModel(
            name='ChallengeModeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='An exact historical or alternative challenge ID.', max_length=160, unique=True)),
                ('challenge_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='registry.challengemode')),
            ],
            options={
                'verbose_name': 'challenge mode alias',
                'verbose_name_plural': 'challenge mode aliases',
                'ordering': ('key',),
            },
        ),
    ]
