# Generated by Django 5.2.16 on 2026-07-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_challenge_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengerun',
            name='starting_challenge_game_mode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='challengerun',
            name='starting_challenge_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='challengerun',
            name='starting_challenge_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_runs', to='registry.challengemode'),
        ),
    ]
