# Generated by Django 5.2.16 on 2026-08-01 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_workshopmod_review_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopModVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=150)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('disallow', 'Disallow'), ('discuss', 'Discuss')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_mod_votes', to=settings.AUTH_USER_MODEL)),
                ('workshop_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_votes', to='registry.workshopmod')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('workshop_mod', 'voter'), name='one_vote_per_team_member_per_workshop_mod')],
            },
        ),
    ]
