# Generated by Django 5.2.16 on 2026-08-03 02:14

import django.db.models.deletion
import json
from datetime import datetime
from pathlib import Path
from django.conf import settings
from django.db import migrations, models


def import_packaged_snapshot(apps, schema_editor):
    Entry = apps.get_model("registry", "LegacyLeaderboardEntry")
    path = Path(__file__).resolve().parent.parent / "data" / "legacy_hall_of_fame.json"
    snapshot = json.loads(path.read_text(encoding="utf-8"))
    captured_at = datetime.fromisoformat(snapshot["captured_at"])
    for item in snapshot["entries"]:
        Entry.objects.update_or_create(
            source_key=item["source_key"],
            defaults={
                **{key: value for key, value in item.items() if key != "source_key"},
                "snapshot_id": snapshot["snapshot_id"],
                "snapshot_captured_at": captured_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_workshopmodvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('source_row', models.PositiveIntegerField()),
                ('source_rank', models.PositiveIntegerField(db_index=True)),
                ('historical_name', models.CharField(db_index=True, max_length=160)),
                ('zombie_kills', models.PositiveBigIntegerField(default=0)),
                ('survival_time_full', models.CharField(blank=True, max_length=32)),
                ('survival_days', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('kills_per_day', models.DecimalField(decimal_places=5, default=0, max_digits=14)),
                ('playtime_hours', models.DecimalField(decimal_places=5, default=0, max_digits=14)),
                ('outposts_cleared', models.PositiveSmallIntegerField(default=0)),
                ('maxed_skills', models.PositiveSmallIntegerField(default=0)),
                ('challenge_progress', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('source_url', models.TextField(blank=True)),
                ('snapshot_id', models.CharField(max_length=120)),
                ('snapshot_captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_legacy_leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'legacy Hall of Fame entry',
                'verbose_name_plural': 'legacy Hall of Fame entries',
                'ordering': ('source_rank', 'historical_name'),
            },
        ),
        migrations.CreateModel(
            name='LegacyLeaderboardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('evidence', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_leaderboard_claims', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_legacy_leaderboard_claims', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='registry.legacyleaderboardentry')),
            ],
            options={
                'ordering': ('-submitted_at',),
                'constraints': [models.UniqueConstraint(fields=('entry', 'participant'), name='unique_legacy_entry_participant_claim')],
            },
        ),
        migrations.RunPython(import_packaged_snapshot, migrations.RunPython.noop),
    ]
