# Generated by Django 5.2.16 on 2026-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_participant_primary_streaming_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemode',
            name='max_active_runs_per_participant',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum active runs each participant may have in this challenge mode. Updates to an existing active run do not use another slot.'),
        ),
        migrations.AddField(
            model_name='challengerun',
            name='participant_deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
