# Generated by Django 5.2.16 on 2026-08-04 00:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0031_challenge_mode_active_run_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacyleaderboardentry',
            name='claimed_participant',
        ),
        migrations.CreateModel(
            name='LegacyDataImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('preview', 'Awaiting confirmation'), ('imported', 'Imported'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='preview', max_length=16)),
                ('leaderboard_filename', models.CharField(max_length=255)),
                ('hall_of_fame_filename', models.CharField(max_length=255)),
                ('leaderboard_sha256', models.CharField(max_length=64)),
                ('hall_of_fame_sha256', models.CharField(max_length=64)),
                ('leaderboard_csv', models.TextField()),
                ('hall_of_fame_csv', models.TextField()),
                ('preview', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_data_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'legacy data import',
                'verbose_name_plural': 'legacy data imports',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='LegacyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('legacy_participant_name', models.CharField(db_index=True, max_length=160)),
                ('normalized_legacy_name', models.CharField(editable=False, max_length=160, unique=True)),
                ('lifecycle', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased')], db_index=True, default='active', max_length=16)),
                ('character_name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_legacy_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'legacy run',
                'verbose_name_plural': 'legacy runs',
                'ordering': ('legacy_participant_name',),
            },
        ),
        migrations.CreateModel(
            name='LegacyRunClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('evidence', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_run_claims', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_legacy_run_claims', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='registry.legacyrun')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='LegacyRunSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('approved', 'Approved'), ('declined', 'Declined')], default='received', max_length=16)),
                ('source', models.CharField(choices=[('import_leaderboard', 'Imported Legacy Leaderboard'), ('import_hall_of_fame', 'Imported Legacy Hall of Fame'), ('participant', 'Participant submission')], max_length=24)),
                ('source_rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('character_name', models.CharField(blank=True, max_length=160)),
                ('zombie_kills', models.PositiveBigIntegerField(default=0)),
                ('survival_days', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('outposts_cleared', models.PositiveSmallIntegerField(default=0)),
                ('maxed_skills', models.PositiveSmallIntegerField(default=0)),
                ('challenge_progress', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('import_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_submissions', to='registry.legacydataimport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_legacy_run_submissions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='registry.legacyrun')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_run_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.AddField(
            model_name='legacyrun',
            name='best_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_runs', to='registry.legacyrunsubmission'),
        ),
        migrations.AddField(
            model_name='legacyrun',
            name='current_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_runs', to='registry.legacyrunsubmission'),
        ),
        migrations.DeleteModel(
            name='LegacyLeaderboardClaim',
        ),
        migrations.DeleteModel(
            name='LegacyLeaderboardEntry',
        ),
        migrations.AddConstraint(
            model_name='legacyrunclaim',
            constraint=models.UniqueConstraint(fields=('run', 'participant'), name='unique_legacy_run_participant_claim'),
        ),
    ]
