# Generated by Django 5.2.17 on 2026-08-15 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_run_initial_authority'),
        ('zomboid_catalogue', '0009_seed_tgsrr_geography'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunOutpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_completed_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_completed_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_completed_world_age_hours', models.FloatField(blank=True, null=True)),
                ('first_completed_elapsed_days', models.FloatField(blank=True, null=True)),
                ('latest_completed_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_completed_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_completed_world_age_hours', models.FloatField(blank=True, null=True)),
                ('latest_completed_elapsed_days', models.FloatField(blank=True, null=True)),
                ('latest_regressed_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_regressed_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_regressed_world_age_hours', models.FloatField(blank=True, null=True)),
                ('latest_regressed_elapsed_days', models.FloatField(blank=True, null=True)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('regression_count', models.PositiveIntegerField(default=0)),
                ('current_state', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], max_length=16)),
                ('raw_outpost_id', models.CharField(max_length=255)),
                ('discovered', models.BooleanField(default=False)),
                ('discovered_world_age_hours', models.FloatField(default=0)),
                ('stage', models.CharField(max_length=32)),
                ('complete', models.BooleanField(default=False)),
                ('progress', models.FloatField(default=0)),
                ('passed_requirements', models.PositiveSmallIntegerField(default=0)),
                ('total_requirements', models.PositiveSmallIntegerField(default=0)),
                ('work_started_world_age_hours', models.FloatField(default=0)),
                ('catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_outpost_records', to='zomboid_catalogue.catalogueentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoritative_outposts', to='registry.challengerun')),
            ],
        ),
        migrations.CreateModel(
            name='RunOutpostDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_completed_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_completed_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_completed_world_age_hours', models.FloatField(blank=True, null=True)),
                ('first_completed_elapsed_days', models.FloatField(blank=True, null=True)),
                ('latest_completed_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_completed_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_completed_world_age_hours', models.FloatField(blank=True, null=True)),
                ('latest_completed_elapsed_days', models.FloatField(blank=True, null=True)),
                ('latest_regressed_sequence', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_regressed_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('latest_regressed_world_age_hours', models.FloatField(blank=True, null=True)),
                ('latest_regressed_elapsed_days', models.FloatField(blank=True, null=True)),
                ('completion_count', models.PositiveIntegerField(default=0)),
                ('regression_count', models.PositiveIntegerField(default=0)),
                ('current_state', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], max_length=16)),
                ('raw_deliverable_id', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('current_value', models.FloatField(default=0)),
                ('required_value', models.FloatField(default=0)),
                ('observed_state', models.CharField(blank=True, max_length=255)),
                ('progress', models.FloatField(default=0)),
                ('observed_world_age_hours', models.FloatField(default=0)),
                ('catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_outpost_deliverable_records', to='zomboid_catalogue.catalogueentry')),
                ('outpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='registry.runoutpost')),
            ],
        ),
        migrations.AddConstraint(
            model_name='runoutpost',
            constraint=models.UniqueConstraint(fields=('run', 'raw_outpost_id'), name='unique_run_authoritative_outpost'),
        ),
        migrations.AddConstraint(
            model_name='runoutpostdeliverable',
            constraint=models.UniqueConstraint(fields=('outpost', 'raw_deliverable_id'), name='unique_run_outpost_deliverable'),
        ),
    ]
