# Generated by Django 5.2.17 on 2026-08-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_run_outpost_authority'),
        ('zomboid_catalogue', '0009_seed_tgsrr_geography'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunKillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_kills', models.PositiveBigIntegerField(default=0)),
                ('weapon_partial', models.BooleanField(default=False)),
                ('weapon_baseline_total', models.PositiveBigIntegerField(default=0)),
                ('fire_deaths', models.PositiveBigIntegerField(default=0)),
                ('fire_deaths_partial', models.BooleanField(default=False)),
                ('zombie_kill_types_partial', models.BooleanField(default=False)),
                ('standing', models.PositiveBigIntegerField(default=0)),
                ('on_front', models.PositiveBigIntegerField(default=0)),
                ('on_back', models.PositiveBigIntegerField(default=0)),
                ('fence_assist', models.PositiveBigIntegerField(default=0)),
                ('window_assist', models.PositiveBigIntegerField(default=0)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kill_summary', to='registry.challengerun')),
            ],
        ),
        migrations.CreateModel(
            name='RunSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_skill_id', models.CharField(max_length=255)),
                ('raw_category_id', models.CharField(blank=True, max_length=255)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('xp', models.FloatField(default=0)),
                ('catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_skill_records', to='zomboid_catalogue.catalogueentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoritative_skills', to='registry.challengerun')),
            ],
            options={
                'ordering': ('raw_category_id', 'raw_skill_id'),
                'constraints': [models.UniqueConstraint(fields=('run', 'raw_skill_id'), name='unique_run_authoritative_skill')],
            },
        ),
        migrations.CreateModel(
            name='RunWeaponKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_source_id', models.CharField(max_length=255)),
                ('kills', models.PositiveBigIntegerField(default=0)),
                ('catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_weapon_kill_records', to='zomboid_catalogue.catalogueentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_kills', to='registry.challengerun')),
            ],
            options={
                'ordering': ('-kills', 'raw_source_id'),
                'constraints': [models.UniqueConstraint(fields=('run', 'raw_source_id'), name='unique_run_weapon_kill_source')],
            },
        ),
    ]
