# Generated by Django 5.2.17 on 2026-08-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_run_skills_and_kills'),
        ('zomboid_catalogue', '0009_seed_tgsrr_geography'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('sealed', 'Sealed'), ('active', 'Active')], max_length=12)),
                ('day_index', models.PositiveIntegerField()),
                ('calendar_year', models.PositiveIntegerField(blank=True, null=True)),
                ('calendar_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calendar_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('started_world_age_hours', models.FloatField(blank=True, null=True)),
                ('observed_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('observed_world_age_hours', models.FloatField(blank=True, null=True)),
                ('elapsed_world_hours', models.FloatField(blank=True, null=True)),
                ('partial', models.BooleanField(default=False)),
                ('partial_metrics', models.JSONField(blank=True, default=list)),
                ('kill_delta', models.BigIntegerField(default=0)),
                ('weight_delta_kilograms', models.FloatField(default=0)),
                ('fire_death_delta', models.BigIntegerField(default=0)),
                ('distance_delta_meters', models.FloatField(default=0)),
                ('butter_produced_delta', models.BigIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='registry.challengerun')),
            ],
            options={
                'ordering': ('day_index', 'state'),
            },
        ),
        migrations.CreateModel(
            name='RunDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('skill_xp', 'Skill XP'), ('weapon_kill', 'Weapon kill'), ('broken_weapon', 'Broken weapon'), ('animal_slaughter', 'Animal slaughter'), ('animal_trap', 'Animal trap'), ('animal_birth', 'Animal birth'), ('milk_collected', 'Milk collected'), ('fish_caught', 'Fish caught'), ('injury', 'Injury'), ('zombie_associated_injury', 'Zombie-associated injury')], max_length=32)),
                ('raw_primary_id', models.CharField(max_length=255)),
                ('raw_secondary_id', models.CharField(blank=True, max_length=255)),
                ('value', models.FloatField()),
                ('primary_catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_run_daily_metrics', to='zomboid_catalogue.catalogueentry')),
                ('secondary_catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_run_daily_metrics', to='zomboid_catalogue.catalogueentry')),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='registry.rundailyrecord')),
            ],
            options={
                'ordering': ('kind', 'raw_primary_id', 'raw_secondary_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='rundailyrecord',
            constraint=models.UniqueConstraint(fields=('run', 'state', 'day_index'), name='unique_run_daily_record_state'),
        ),
        migrations.AddConstraint(
            model_name='rundailyrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('run',), name='unique_active_daily_record_per_run'),
        ),
        migrations.AddConstraint(
            model_name='rundailymetric',
            constraint=models.UniqueConstraint(fields=('daily_record', 'kind', 'raw_primary_id', 'raw_secondary_id'), name='unique_run_daily_metric_dimension'),
        ),
    ]
