# Generated by Django 5.2.17 on 2026-08-17 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0042_backfill_run_landmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedRunEventBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('first_sequence', models.PositiveBigIntegerField()),
                ('last_sequence', models.PositiveBigIntegerField()),
                ('event_count', models.PositiveIntegerField()),
                ('starting_hash', models.CharField(max_length=64)),
                ('last_hash', models.CharField(max_length=64)),
                ('canonical', models.BinaryField()),
                ('events', models.JSONField(default=list)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('first_sequence',),
                'constraints': [models.UniqueConstraint(fields=('checksum', 'first_sequence', 'starting_hash', 'last_hash'), name='unique_verified_run_event_block')],
            },
        ),
        migrations.CreateModel(
            name='RunSubmissionEventBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_blocks', to='registry.runsubmission')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_uses', to='registry.verifiedruneventblock')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('submission', 'position'), name='unique_run_submission_event_block_position')],
            },
        ),
    ]
