# Generated by Django 5.2.17 on 2026-08-18 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0043_verifiedruneventblock_runsubmissioneventblock'),
        ('zomboid_catalogue', '0009_seed_tgsrr_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundailyrecord',
            name='active_gameplay_milliseconds_delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rundailyrecord',
            name='calories_consumed_delta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rundailyrecord',
            name='generator_condition_restored_delta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rundailyrecord',
            name='generator_repair_delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rundailyrecord',
            name='nimble_movement_milliseconds_delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rundailymetric',
            name='kind',
            field=models.CharField(choices=[('skill_xp', 'Skill XP'), ('weapon_kill', 'Weapon kill'), ('broken_weapon', 'Broken weapon'), ('animal_slaughter', 'Animal slaughter'), ('animal_trap', 'Animal trap'), ('animal_birth', 'Animal birth'), ('animal_pet', 'Animal pet'), ('milk_collected', 'Milk collected'), ('fluid_consumed', 'Fluid consumed'), ('fish_caught', 'Fish caught'), ('injury', 'Injury'), ('zombie_associated_injury', 'Zombie-associated injury')], max_length=32),
        ),
        migrations.CreateModel(
            name='RunStatisticSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weight', 'Weight'), ('distance', 'Distance travelled'), ('nimble_stance', 'Nimble stance movement'), ('active_gameplay', 'Active gameplay'), ('broken_weapons', 'Broken weapons'), ('animal_slaughter', 'Animals slaughtered'), ('animal_trap', 'Animals trapped'), ('animal_birth', 'Animal births'), ('animal_pet', 'Animals petted'), ('milk_collected', 'Milk collected'), ('fluid_consumed', 'Fluid consumed'), ('calories_consumed', 'Calories consumed'), ('butter_produced', 'Butter produced'), ('fish_caught', 'Fish caught'), ('injuries', 'Injuries'), ('zombie_associated_injuries', 'Zombie-associated injuries'), ('generator_repairs', 'Generator repairs')], max_length=40)),
                ('value', models.FloatField(default=0)),
                ('secondary_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('partial', models.BooleanField(default=False)),
                ('raw_reference_id', models.CharField(blank=True, max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_summaries', to='registry.challengerun')),
            ],
            options={
                'ordering': ('kind',),
            },
        ),
        migrations.CreateModel(
            name='RunStatisticMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('item', 'Item'), ('animal', 'Animal'), ('trap', 'Trap'), ('animal_trap', 'Animal and trap'), ('fluid', 'Fluid'), ('injury_type', 'Injury type'), ('body_part', 'Body part'), ('injury_pair', 'Injury and body part')], max_length=24)),
                ('raw_primary_id', models.CharField(max_length=255)),
                ('raw_secondary_id', models.CharField(blank=True, max_length=255)),
                ('value', models.FloatField(default=0)),
                ('primary_catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_run_statistic_metrics', to='zomboid_catalogue.catalogueentry')),
                ('secondary_catalogue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_run_statistic_metrics', to='zomboid_catalogue.catalogueentry')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='registry.runstatisticsummary')),
            ],
            options={
                'ordering': ('dimension', 'raw_primary_id', 'raw_secondary_id'),
            },
        ),
        migrations.AddIndex(
            model_name='runstatisticsummary',
            index=models.Index(fields=['kind', 'value'], name='registry_ru_kind_6d5dc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='runstatisticsummary',
            constraint=models.UniqueConstraint(fields=('run', 'kind'), name='unique_run_statistic_summary'),
        ),
        migrations.AddIndex(
            model_name='runstatisticmetric',
            index=models.Index(fields=['dimension', 'raw_primary_id'], name='registry_ru_dimensi_466b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='runstatisticmetric',
            index=models.Index(fields=['dimension', 'raw_secondary_id'], name='registry_ru_dimensi_750b04_idx'),
        ),
        migrations.AddConstraint(
            model_name='runstatisticmetric',
            constraint=models.UniqueConstraint(fields=('summary', 'dimension', 'raw_primary_id', 'raw_secondary_id'), name='unique_run_statistic_metric_dimension'),
        ),
    ]
