# Generated by Django 5.2.17 on 2026-08-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0044_rundailyrecord_active_gameplay_milliseconds_delta_and_more'),
        ('zomboid_catalogue', '0009_seed_tgsrr_geography'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rundailymetric',
            index=models.Index(fields=['kind', 'raw_primary_id'], name='registry_ru_kind_1abc59_idx'),
        ),
        migrations.AddIndex(
            model_name='rundailymetric',
            index=models.Index(fields=['kind', 'raw_secondary_id'], name='registry_ru_kind_1056f4_idx'),
        ),
    ]
