# Generated by Django 5.2.17 on 2026-08-25 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reported_lifecycle(apps, schema_editor):
    ChallengeRun = apps.get_model("registry", "ChallengeRun")
    RunSubmission = apps.get_model("registry", "RunSubmission")
    for submission in RunSubmission.objects.all().iterator():
        projection = submission.projection if isinstance(submission.projection, dict) else {}
        if projection.get("lifecycle") == "deceased" and projection.get("endedReason") == "deceased":
            submission.reported_lifecycle_status = "deceased"
            submission.save(update_fields=("reported_lifecycle_status",))
    for run in ChallengeRun.objects.all().iterator():
        latest_pending = RunSubmission.objects.filter(
            run_id=run.pk, status="received"
        ).order_by("-event_sequence", "-generated_at").first()
        run.reported_lifecycle_status = (
            latest_pending.reported_lifecycle_status
            if latest_pending
            else run.lifecycle_status
        )
        run.save(update_fields=("reported_lifecycle_status",))


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0045_rundailymetric_registry_ru_kind_1abc59_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemode',
            name='max_pending_deceased_runs_per_participant',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Maximum pending deceased runs per participant. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='challengerun',
            name='reported_lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('deceased', 'Deceased'), ('abandoned', 'Abandoned'), ('completed', 'Completed'), ('invalidated', 'Invalidated')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='reported_lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('deceased', 'Deceased'), ('abandoned', 'Abandoned'), ('completed', 'Completed'), ('invalidated', 'Invalidated')], default='active', max_length=16),
        ),
        migrations.RunPython(backfill_reported_lifecycle, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ParticipantChallengeModeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_active_runs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_pending_deceased_runs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_limits', to='registry.challengemode')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_mode_limits', to=settings.AUTH_USER_MODEL)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'challenge_mode'), name='unique_participant_challenge_mode_limit')],
            },
        ),
    ]
