# Generated by Django 5.2.17 on 2026-08-29 16:13

from django.db import migrations, models


def capture_existing_preapproval_assessments(apps, schema_editor):
    HistoricalRunSubmission = apps.get_model("registry", "RunSubmission")
    if not HistoricalRunSubmission.objects.exists():
        return

    from registry.models import RunSubmission
    from registry.run_review import capture_preapproval_assessment

    submissions = RunSubmission.objects.select_related(
        "run",
        "run__approved_submission",
        "baseline_submission",
        "challenge_mode",
    ).defer(
        "reviewed_by",
        "evidence_requested_at",
        "evidence_requested_by",
        "evidence_request_note",
    )
    for submission in submissions.iterator():
        capture_preapproval_assessment(submission)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0046_challengemode_max_pending_deceased_runs_per_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsubmission',
            name='preapproval_assessed_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='preapproval_findings',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='preapproval_state',
            field=models.CharField(choices=[('green', 'All checks passed'), ('orange', 'Needs attention'), ('red', 'Blocking issue')], default='red', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='preapproval_version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.RunPython(
            capture_existing_preapproval_assessments,
            migrations.RunPython.noop,
        ),
    ]
