# Generated by Django 5.2.17 on 2026-09-01 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initial_evidence_revisions(apps, schema_editor):
    RunSubmission = apps.get_model("registry", "RunSubmission")
    EvidenceRevision = apps.get_model(
        "registry", "RunSubmissionEvidenceRevision"
    )
    revisions = []
    for submission in RunSubmission.objects.all().iterator(chunk_size=500):
        revisions.append(
            EvidenceRevision(
                submission_id=submission.pk,
                source="initial",
                evidence_provider=submission.evidence_provider,
                evidence_media_type=submission.evidence_media_type,
                evidence_media_id=submission.evidence_media_id,
                evidence_url=submission.evidence_url,
                evidence_title=submission.evidence_title,
                evidence_start_seconds=submission.evidence_start_seconds,
                evidence_end_seconds=submission.evidence_end_seconds,
                evidence_clips=submission.evidence_clips,
                created_at=submission.submitted_at,
            )
        )
        if len(revisions) == 500:
            EvidenceRevision.objects.bulk_create(revisions)
            revisions = []
    if revisions:
        EvidenceRevision.objects.bulk_create(revisions)


def remove_evidence_revisions(apps, schema_editor):
    apps.get_model("registry", "RunSubmissionEvidenceRevision").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0049_rename_standard_challenge_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_request_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_requested_run_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_run_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runsubmission',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('awaiting_evidence', 'Awaiting evidence'), ('approved', 'Approved'), ('declined', 'Declined')], default='received', max_length=20),
        ),
        migrations.CreateModel(
            name='RunSubmissionEvidenceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('initial', 'Initial submission'), ('participant', 'Participant update')], max_length=16)),
                ('evidence_provider', models.CharField(blank=True, max_length=16)),
                ('evidence_media_type', models.CharField(blank=True, max_length=12)),
                ('evidence_media_id', models.CharField(blank=True, max_length=255)),
                ('evidence_url', models.URLField(blank=True, max_length=1000)),
                ('evidence_title', models.CharField(blank=True, max_length=500)),
                ('evidence_start_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_end_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_clips', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_revisions', to='registry.runsubmission')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.RunPython(
            backfill_initial_evidence_revisions,
            remove_evidence_revisions,
        ),
    ]
