# Generated by Django 5.2.17 on 2026-09-11 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0050_submission_evidence_corrections'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Submission Audit',
                'verbose_name_plural': 'Submission Audits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registry.runsubmission',),
        ),
        migrations.AlterModelOptions(
            name='runsubmission',
            options={'ordering': ('-submitted_at',), 'verbose_name_plural': 'Submission Reviews'},
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='approval_method',
            field=models.CharField(blank=True, choices=[('human', 'Moderator approved'), ('automatic', 'Auto-Approved')], editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='approval_policy_version',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_check',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='evidence_checked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='runsubmission',
            name='routing_reasons',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.CreateModel(
            name='SubmissionAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('selected', 'Selected'), ('in_progress', 'In progress'), ('passed', 'Passed'), ('action_required', 'Action required')], max_length=20)),
                ('evidence_intervals', models.TextField(blank=True, help_text='Video links and time intervals actually inspected.')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='registry.runsubmission')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
