# Generated by Django 5.2.17 on 2026-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0051_submission_approval_and_audits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runsubmission',
            name='status',
            field=models.CharField(choices=[('received', 'Pending Approval'), ('awaiting_evidence', 'Awaiting evidence'), ('approved', 'Approved'), ('declined', 'Declined')], default='received', max_length=20),
        ),
    ]
