# Generated by Django 5.2.17 on 2026-09-11 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0052_submission_pending_approval_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('shared', models.BooleanField(default=False)),
                ('filters', models.JSONField(default=dict)),
                ('system_key', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': [('manage_shared_run_views', 'Can manage shared Challenge Runs views')],
            },
        ),
        migrations.CreateModel(
            name='RunWorkspacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.runsavedview')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RunViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.runsavedview')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'view'), name='unique_user_run_view')],
            },
        ),
    ]
