# Generated by Django 5.2.17 on 2026-09-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0055_shared_run_view_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemode',
            name='evidence_required',
            field=models.BooleanField(default=True, help_text='Require a Twitch or YouTube VOD for submission and manual approval. Automatic approval always requires verified evidence.'),
        ),
    ]
