# Generated by Django 5.2.17 on 2026-09-12 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_views(apps, schema_editor):
    View = apps.get_model('registry', 'ParticipantSavedView')
    for key, name, filters in [
        ('all', 'All', {}),
        ('pending', 'Pending verification', {'status__exact': 'pending'}),
        ('verified', 'Verified', {'status__exact': 'verified'}),
        ('avatars', 'Pending avatar review', {'avatar_status__exact': 'pending'}),
    ]:
        View.objects.create(system_key=key, name=name, shared=True, filters=filters)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0057_active_audit_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('shared', models.BooleanField(default=False)),
                ('filters', models.JSONField(default=dict)),
                ('system_key', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': [('manage_shared_participant_views', 'Can manage shared Participant views')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantWorkspacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.participantsavedview')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.participantsavedview')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'view'), name='unique_user_participant_view')],
            },
        ),
        migrations.RunPython(seed_views, migrations.RunPython.noop),
    ]
