# Generated by Django 5.2.17 on 2026-09-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_views(apps, schema_editor):
    View = apps.get_model('registry', 'WorkshopModSavedView')
    for key, label in [('pending', 'Pending Review'), ('allowed', 'Allowed'), ('disallowed', 'Disallowed'), ('all', 'All')]:
        View.objects.create(system_key=key, name=label, shared=True, filters={'ruling__exact': key} if key != 'all' else {})


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0058_participant_saved_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopModSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('shared', models.BooleanField(default=False)),
                ('filters', models.JSONField(default=dict)),
                ('system_key', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_mod_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': [('manage_shared_workshop_mod_views', 'Can manage shared Workshop Mod views')],
            },
        ),
        migrations.CreateModel(
            name='WorkshopModWorkspacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.workshopmodsavedview')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopModViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.workshopmodsavedview')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('user', 'view'), name='unique_user_workshop_mod_view')],
            },
        ),
        migrations.RunPython(seed_views, migrations.RunPython.noop),
    ]
