# Generated by Django 5.2.17 on 2026-09-20 12:58

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0059_workshopmodsavedview_workshopmodworkspacepreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
