# Generated by Django 5.2.17 on 2026-09-20 13:06

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0060_participant_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country / territory'),
        ),
    ]
