# Generated by Django 5.2.16 on 2026-07-28 12:39

import django.db.models.deletion
import zomboid_catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomboid_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='kind',
            field=models.CharField(choices=[('skill', 'Skill'), ('trait', 'Trait'), ('occupation', 'Occupation'), ('item', 'Item'), ('recipe', 'Recipe'), ('town', 'Town'), ('location', 'Location'), ('outpost', 'Outpost'), ('deliverable', 'Deliverable'), ('mod', 'Mod')], max_length=24),
        ),
        migrations.CreateModel(
            name='OccupationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_cost', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('granted_traits', models.JSONField(blank=True, default=list)),
                ('xp_boosts', models.JSONField(blank=True, default=dict)),
                ('granted_recipes', models.JSONField(blank=True, default=list)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_details', to='zomboid_catalogue.catalogueentry')),
            ],
            options={
                'verbose_name': 'occupation details',
                'verbose_name_plural': 'occupation details',
            },
        ),
        migrations.CreateModel(
            name='SkillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('parent_skill_id', models.CharField(blank=True, max_length=120)),
                ('level_xp', models.JSONField(blank=True, default=list)),
                ('is_passive', models.BooleanField(default=False)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_details', to='zomboid_catalogue.catalogueentry')),
            ],
            options={
                'verbose_name': 'skill details',
                'verbose_name_plural': 'skill details',
            },
        ),
        migrations.CreateModel(
            name='TraitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_cost', models.SmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_profession_trait', models.BooleanField(default=False)),
                ('disabled_in_multiplayer', models.BooleanField(default=False)),
                ('xp_boosts', models.JSONField(blank=True, default=dict)),
                ('mutually_exclusive_traits', models.JSONField(blank=True, default=list)),
                ('granted_recipes', models.JSONField(blank=True, default=list)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trait_details', to='zomboid_catalogue.catalogueentry')),
            ],
            options={
                'verbose_name': 'trait details',
                'verbose_name_plural': 'trait details',
            },
        ),
        migrations.CreateModel(
            name='CatalogueAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('icon', 'Icon'), ('screenshot', 'Screenshot'), ('illustration', 'Illustration')], default='icon', max_length=24)),
                ('source_key', models.CharField(help_text='Project Zomboid texture key or other deterministic source identifier.', max_length=255)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('file', models.ImageField(blank=True, upload_to=zomboid_catalogue.models.catalogue_asset_upload_to)),
                ('availability', models.CharField(choices=[('imported', 'Imported'), ('packed', 'Packed in game texture archive'), ('missing', 'Not found')], default='missing', max_length=16)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='zomboid_catalogue.catalogueentry')),
            ],
            options={
                'ordering': ('sort_order', 'role', 'source_key'),
                'constraints': [models.UniqueConstraint(fields=('entry', 'role', 'source_key'), name='unique_catalogue_asset_source')],
            },
        ),
    ]
