# Generated by Django 5.2.16 on 2026-07-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomboid_catalogue', '0002_alter_catalogueentry_kind_occupationdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueentry',
            name='kind',
            field=models.CharField(choices=[('skill', 'Skill'), ('trait', 'Trait'), ('occupation', 'Occupation'), ('item', 'Item'), ('recipe', 'Recipe'), ('town', 'Town'), ('location', 'Location'), ('animal', 'Animal'), ('outpost', 'Outpost'), ('deliverable', 'Deliverable'), ('mod', 'Mod')], max_length=24),
        ),
        migrations.CreateModel(
            name='AnimalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.CharField(help_text='Website-owned stable species identifier used for grouping.', max_length=120)),
                ('species_name', models.CharField(max_length=120)),
                ('life_stage', models.CharField(blank=True, choices=[('baby', 'Baby'), ('juvenile', 'Juvenile'), ('adult', 'Adult')], max_length=16)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal_details', to='zomboid_catalogue.catalogueentry')),
            ],
            options={
                'verbose_name': 'animal details',
                'verbose_name_plural': 'animal details',
                'ordering': ('species_name', 'life_stage', 'entry__display_name'),
            },
        ),
    ]
