# Generated by Django 5.2.16 on 2026-07-28 23:53

import django.db.models.deletion
from django.db import migrations, models


def move_typed_categories(apps, schema_editor):
    CatalogueEntry = apps.get_model("zomboid_catalogue", "CatalogueEntry")
    AnimalDetails = apps.get_model("zomboid_catalogue", "AnimalDetails")
    DeliverableDetails = apps.get_model("zomboid_catalogue", "DeliverableDetails")

    for details in AnimalDetails.objects.select_related("entry"):
        details.category = details.entry.category
        details.save(update_fields=("category",))
    for entry in CatalogueEntry.objects.filter(kind="deliverable"):
        DeliverableDetails.objects.update_or_create(
            entry=entry,
            defaults={"category": entry.category},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('zomboid_catalogue', '0003_alter_catalogueentry_kind_animaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaldetails',
            name='category',
            field=models.CharField(blank=True, help_text='Website-owned animal grouping, such as Mammal or Bird.', max_length=120),
        ),
        migrations.RenameField(
            model_name='skilldetails',
            old_name='parent_skill_id',
            new_name='category',
        ),
        migrations.CreateModel(
            name='DeliverableDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='Rat Race grouping for this deliverable or objective.', max_length=120)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_details', to='zomboid_catalogue.catalogueentry')),
            ],
            options={
                'verbose_name': 'deliverable details',
                'verbose_name_plural': 'deliverable details',
            },
        ),
        migrations.RunPython(move_typed_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='catalogueentry',
            name='category',
        ),
        migrations.AlterField(
            model_name='skilldetails',
            name='category',
            field=models.CharField(blank=True, help_text='The Project Zomboid skill category identifier.', max_length=120),
        ),
    ]
