# Generated by Django 5.2.16 on 2026-07-29 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomboid_catalogue', '0005_itemdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDisplayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(help_text='The exact Project Zomboid DisplayCategory identifier.', max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'item display category',
                'verbose_name_plural': 'item display categories',
                'ordering': ('display_name', 'stable_id'),
            },
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='weapon_skill',
            field=models.ForeignKey(blank=True, help_text='Skill deterministically resolved from Project Zomboid weapon evidence.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weapon_items', to='zomboid_catalogue.skilldetails'),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='display_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='zomboid_catalogue.itemdisplaycategory'),
        ),
    ]
