# Generated by Django 5.2.16 on 2026-07-29 01:44

from django.db import migrations, models


def classify_existing_assets(apps, schema_editor):
    CatalogueAsset = apps.get_model("zomboid_catalogue", "CatalogueAsset")
    for asset in CatalogueAsset.objects.all().iterator():
        source_path = str(asset.source_path or "")
        if source_path.startswith(("https://", "http://")):
            asset.source_type = "pzwiki"
        elif asset.file and asset.availability == "imported":
            asset.source_type = "game"
            asset.game_availability = "unpacked"
            asset.game_source_path = source_path
            asset.game_source_checksum = asset.source_checksum
        elif asset.availability == "packed":
            asset.game_availability = "packed"
        asset.save(
            update_fields=(
                "source_type",
                "game_availability",
                "game_source_path",
                "game_source_checksum",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('zomboid_catalogue', '0006_itemdisplaycategory_alter_itemdetails_weapon_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueasset',
            name='game_availability',
            field=models.CharField(choices=[('unknown', 'Not checked'), ('unpacked', 'Unpacked file available'), ('packed', 'Packed texture reference only'), ('missing', 'Not found')], default='unknown', help_text='Whether Project Zomboid exposes an accessible file or only a packed reference.', max_length=16),
        ),
        migrations.AddField(
            model_name='catalogueasset',
            name='game_source_checksum',
            field=models.CharField(blank=True, help_text='Checksum of the authoritative loose Project Zomboid file when available.', max_length=64),
        ),
        migrations.AddField(
            model_name='catalogueasset',
            name='game_source_path',
            field=models.CharField(blank=True, help_text='The authoritative loose Project Zomboid file path when available.', max_length=500),
        ),
        migrations.AddField(
            model_name='catalogueasset',
            name='source_type',
            field=models.CharField(choices=[('unknown', 'No served image'), ('game', 'Project Zomboid'), ('pzwiki', 'PZwiki'), ('manual', 'Manual override')], default='unknown', help_text='Provenance of the image currently served by the website.', max_length=16),
        ),
        migrations.RunPython(classify_existing_assets, migrations.RunPython.noop),
    ]
