# Generated by Django 5.2.16 on 2026-08-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomboid_catalogue', '0007_catalogueasset_game_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('outpost', 'Outpost'), ('landmark', 'Landmark'), ('start_area', 'Starting area'), ('town', 'Town')], max_length=16)),
                ('game_version', models.CharField(max_length=32)),
                ('registry_version', models.PositiveIntegerField(default=1)),
                ('anchor_x', models.IntegerField()),
                ('anchor_y', models.IntegerField()),
                ('anchor_z', models.IntegerField(default=0)),
                ('min_x', models.IntegerField(blank=True, null=True)),
                ('min_y', models.IntegerField(blank=True, null=True)),
                ('max_x', models.IntegerField(blank=True, null=True)),
                ('max_y', models.IntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_versions', to='zomboid_catalogue.catalogueentry')),
            ],
            options={
                'ordering': ('location_type', 'entry__display_name', 'game_version'),
            },
        ),
        migrations.CreateModel(
            name='MapLocationBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(help_text='The raw BuildingDef ID observed in this exact game/map version.', max_length=160)),
                ('location_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='zomboid_catalogue.maplocationversion')),
            ],
            options={
                'ordering': ('building_id',),
            },
        ),
        migrations.AddConstraint(
            model_name='maplocationversion',
            constraint=models.UniqueConstraint(fields=('entry', 'game_version', 'registry_version'), name='unique_map_location_version'),
        ),
        migrations.AddConstraint(
            model_name='maplocationbuilding',
            constraint=models.UniqueConstraint(fields=('location_version', 'building_id'), name='unique_map_location_building'),
        ),
    ]
