# Generated by Django 5.2.16 on 2026-07-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='An internal name used in administration.', max_length=120)),
                ('slug', models.SlugField(help_text="The page address. The homepage uses 'home'.", max_length=120, unique=True)),
                ('is_published', models.BooleanField(default=True, help_text='Only published pages can be shown publicly.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'Introduction and actions'), ('steps', 'Numbered information cards')], max_length=24)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('small_heading', models.CharField(blank=True, max_length=160)),
                ('main_heading', models.CharField(blank=True, max_length=240)),
                ('introduction', models.TextField(blank=True, max_length=1000)),
                ('visitor_primary_button', models.CharField(blank=True, max_length=80)),
                ('visitor_secondary_link', models.CharField(blank=True, max_length=80)),
                ('signed_in_button', models.CharField(blank=True, max_length=80)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'verbose_name': 'page section',
                'verbose_name_plural': 'page sections',
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('heading', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pagesection')),
            ],
            options={
                'verbose_name': 'section item',
                'verbose_name_plural': 'section items',
                'ordering': ('position', 'pk'),
            },
        ),
    ]
