# Generated by Django 5.2.16 on 2026-07-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_managed_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_width',
            field=models.CharField(choices=[('narrow', 'Narrow - focused reading'), ('standard', 'Standard - general content'), ('wide', 'Wide - dashboards and richer layouts'), ('full', 'Full - use the available page width')], default='standard', help_text='The default maximum width used by sections on this page.', max_length=16),
        ),
        migrations.AddField(
            model_name='page',
            name='navigation_label',
            field=models.CharField(blank=True, help_text='Optional shorter wording for navigation menus.', max_length=80),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_navigation',
            field=models.BooleanField(default=False, help_text='Make this page eligible for the public navigation menu.'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='background',
            field=models.CharField(choices=[('default', 'Page background'), ('surface', 'Raised surface'), ('alternate', 'Alternate surface')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='full_bleed_background',
            field=models.BooleanField(default=False, help_text='Extend the section background to the viewport edges while keeping content constrained.'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='layout',
            field=models.CharField(choices=[('single', 'Single column'), ('two', 'Two equal columns'), ('wide_left', 'Two columns - wide left'), ('wide_right', 'Two columns - wide right'), ('three', 'Three columns'), ('four', 'Four columns')], default='single', max_length=16),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='width',
            field=models.CharField(choices=[('inherit', 'Use page width'), ('narrow', 'Narrow'), ('standard', 'Standard'), ('wide', 'Wide'), ('full', 'Full width')], default='inherit', max_length=16),
        ),
    ]
