# Generated by Django 5.2.16 on 2026-07-18 23:36

import django.db.models.deletion
from django.db import migrations, models


def migrate_section_content(apps, schema_editor):
    PageBlock = apps.get_model('pages', 'PageBlock')
    PageSection = apps.get_model('pages', 'PageSection')
    SectionItem = apps.get_model('pages', 'SectionItem')
    for section in PageSection.objects.all().order_by('page_id', 'position', 'pk'):
        position = 0
        definitions = (
            ('small_heading', section.small_heading, 'everyone', 'none', 'default'),
            ('heading', section.main_heading, 'everyone', 'none', 'default'),
            ('text', section.introduction, 'everyone', 'none', 'default'),
            ('action', section.visitor_primary_button, 'visitors', 'register', 'primary'),
            ('action', section.visitor_secondary_link, 'visitors', 'login', 'link'),
            ('action', section.signed_in_button, 'signed_in', 'account', 'primary'),
        )
        for block_type, content, audience, destination, style in definitions:
            if content:
                PageBlock.objects.create(
                    section=section, position=position, column=0,
                    block_type=block_type, content=content, audience=audience,
                    destination=destination, style=style,
                )
                position += 10
        items = SectionItem.objects.filter(section=section)
        if items.exists():
            group = PageBlock.objects.create(
                section=section, position=position, column=0,
                block_type='card_group', content='',
            )
            items.update(block=group)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_content_width_page_navigation_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionitem',
            options={'ordering': ('position', 'pk'), 'verbose_name': 'card', 'verbose_name_plural': 'cards'},
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('column', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('block_type', models.CharField(choices=[('small_heading', 'Small heading'), ('heading', 'Heading'), ('text', 'Text'), ('action', 'Button or link'), ('card_group', 'Card group')], max_length=24)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('visitors', 'Signed-out visitors'), ('signed_in', 'Signed-in participants')], default='everyone', max_length=16)),
                ('destination', models.CharField(choices=[('none', 'No destination'), ('register', 'Sign-up page'), ('login', 'Login page'), ('account', 'Participant account')], default='none', max_length=16)),
                ('style', models.CharField(choices=[('default', 'Standard'), ('primary', 'Primary button'), ('secondary', 'Secondary button'), ('link', 'Text link')], default='default', max_length=16)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.pagesection')),
            ],
            options={
                'verbose_name': 'content block',
                'verbose_name_plural': 'content blocks',
                'ordering': ('column', 'position', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pageblock'),
        ),
        migrations.RunPython(migrate_section_content, migrations.RunPython.noop),
        migrations.RemoveField(model_name='pagesection', name='introduction'),
        migrations.RemoveField(model_name='pagesection', name='main_heading'),
        migrations.RemoveField(model_name='pagesection', name='section_type'),
        migrations.RemoveField(model_name='pagesection', name='signed_in_button'),
        migrations.RemoveField(model_name='pagesection', name='small_heading'),
        migrations.RemoveField(model_name='pagesection', name='visitor_primary_button'),
        migrations.RemoveField(model_name='pagesection', name='visitor_secondary_link'),
        migrations.RemoveField(model_name='sectionitem', name='section'),
        migrations.AlterField(
            model_name='sectionitem', name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pageblock'),
        ),
    ]
