# Generated by Django 5.2.16 on 2026-07-20 09:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0012_sitebranding_background_image_brightness_and_more'),
        ('pages', '0005_pagesection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='alternative text'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_blocks', to='branding.managedimage', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='image_custom_height',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(60)], verbose_name='custom height (rem)'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='image_fit',
            field=models.CharField(choices=[('cover', 'Crop to fill'), ('contain', 'Show whole image')], default='cover', max_length=12),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='image_height',
            field=models.CharField(choices=[('standard', 'Standard - maximum 24rem'), ('natural', 'Natural proportions'), ('short', 'Short banner - 12rem'), ('tall', 'Tall banner - 32rem'), ('custom', 'Custom height')], default='standard', max_length=12),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='image_position',
            field=models.CharField(choices=[('left top', 'Top left'), ('center top', 'Top centre'), ('right top', 'Top right'), ('left center', 'Centre left'), ('center center', 'Centre'), ('right center', 'Centre right'), ('left bottom', 'Bottom left'), ('center bottom', 'Bottom centre'), ('right bottom', 'Bottom right')], default='center center', max_length=20),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('small_heading', 'Small heading'), ('heading', 'Heading'), ('text', 'Text'), ('action', 'Button or link'), ('card_group', 'Card group'), ('image', 'Image')], max_length=24),
        ),
    ]
