# Generated by Django 5.2.16 on 2026-07-20 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0012_sitebranding_background_image_brightness_and_more'),
        ('pages', '0007_migrate_homepage_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='gallery_auto_scroll',
            field=models.BooleanField(default=False, verbose_name='scroll automatically'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='gallery_expandable',
            field=models.BooleanField(default=True, verbose_name='allow expanded view'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='gallery_loop',
            field=models.BooleanField(default=True, verbose_name='loop continuously'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='gallery_scroll_speed',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='scroll interval (seconds)'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='gallery_show_captions',
            field=models.BooleanField(default=True, verbose_name='show captions'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='gallery_show_controls',
            field=models.BooleanField(default=True, verbose_name='show navigation controls'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('small_heading', 'Small heading'), ('heading', 'Heading'), ('text', 'Text'), ('action', 'Button or link'), ('card_group', 'Card group'), ('image', 'Image'), ('gallery', 'Gallery')], max_length=24),
        ),
        migrations.CreateModel(
            name='PageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('alternative_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.pageblock')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_galleries', to='branding.managedimage')),
            ],
            options={
                'ordering': ('position', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('block', 'image'), name='unique_image_per_page_gallery')],
            },
        ),
    ]
