# Generated by Django 5.2.16 on 2026-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_pageblock_gallery_auto_scroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='card_columns',
            field=models.CharField(choices=[('auto', 'Automatic wrapping'), ('1', '1 card per row'), ('2', '2 cards per row'), ('3', '3 cards per row'), ('4', '4 cards per row')], default='auto', max_length=8, verbose_name='cards per row'),
        ),
    ]
