# Generated by Django 5.2.16 on 2026-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_unified_text_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='destination',
            field=models.CharField(choices=[('none', 'No destination'), ('register', 'Sign Up page'), ('login', 'Sign In page'), ('account', 'Participant account')], default='none', max_length=16),
        ),
    ]
