# Generated by Django 5.2.16 on 2026-07-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_pageblock_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='image_expandable',
            field=models.BooleanField(default=False, verbose_name='allow expanded view'),
        ),
    ]
