# Generated by Django 5.2.16 on 2026-07-31 09:38

import django.db.models.deletion
from django.db import migrations, models


def seed_code_managed_pages(apps, schema_editor):
    CodeManagedPage = apps.get_model("pages", "CodeManagedPage")
    definitions = (
        ("top-ten", "Top ten", "Public summary of the ten leading Rat Race records.", "public", "planned", "", "/top-ten/"),
        ("leaderboard", "Current leaderboard", "Public leaderboard containing each participant's active personal best.", "public", "available", "registry:leaderboard", "/leaderboard/"),
        ("approved-mods", "Approved mods", "Public list of mods approved for Rat Race runs.", "public", "planned", "", "/mods/approved/"),
        ("disallowed-mods", "Disallowed mods", "Public list of mods that cannot be used for Rat Race runs.", "public", "planned", "", "/mods/disallowed/"),
        ("run-history", "Run history", "Signed-in, filterable history of all Rat Race runs.", "participant", "planned", "", "/runs/"),
        ("run-detail", "Run details", "Signed-in details and statistics for an individual run.", "participant", "available", "", "/runs/<run-id>/"),
        ("account", "Participant account", "Signed-in participant dashboard and account summary.", "participant", "available", "registry:account", "/account/"),
        ("account-settings", "Account settings", "Signed-in participant settings and connected accounts.", "participant", "available", "registry:account_settings", "/account/settings/"),
        ("notifications", "Notifications", "Signed-in participant notification history.", "participant", "available", "registry:notifications", "/account/notifications/"),
    )
    for key, title, description, audience, availability, route_name, address in definitions:
        CodeManagedPage.objects.update_or_create(
            key=key,
            defaults={
                "title": title,
                "description": description,
                "audience": audience,
                "availability": availability,
                "route_name": route_name,
                "address": address,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_image_block_expanded_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeManagedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(editable=False, help_text='Stable identity owned by version-controlled website code.', max_length=80, unique=True)),
                ('title', models.CharField(editable=False, max_length=120)),
                ('description', models.TextField(editable=False, max_length=500)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('participant', 'Signed-in participant'), ('staff', 'Staff')], editable=False, max_length=16)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('planned', 'Planned'), ('disabled', 'Disabled')], editable=False, max_length=16)),
                ('route_name', models.CharField(blank=True, editable=False, max_length=160)),
                ('address', models.CharField(editable=False, max_length=240)),
            ],
            options={
                'verbose_name': 'code-managed page',
                'verbose_name_plural': 'code-managed pages',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='code_page',
            field=models.ForeignKey(blank=True, help_text='Optional code-managed application destination.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='navigation_items', to='pages.codemanagedpage'),
        ),
        migrations.AddConstraint(
            model_name='navigationitem',
            constraint=models.CheckConstraint(condition=models.Q(('page__isnull', False), ('code_page__isnull', False), _negated=True), name='navigation_item_has_one_destination'),
        ),
        migrations.RunPython(seed_code_managed_pages, migrations.RunPython.noop),
    ]
