# Generated by Django 5.2.16 on 2026-08-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_codemanagedpage_navigationitem_code_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='ranking_config',
            field=models.JSONField(blank=True, default=dict, help_text='Validated filters, result selection, ordering, columns and display controls.', verbose_name='ranking table configuration'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('action', 'Button or link'), ('card_group', 'Card group'), ('image', 'Image'), ('gallery', 'Gallery'), ('ranking_table', 'Ranking table')], max_length=24),
        ),
    ]
