# Generated by Django 5.2.16 on 2026-08-06 00:19

from django.db import migrations, models


STATS_CONFIG = {
    "metrics": [
        "active_runs", "total_kills", "total_days", "outposts_claimed",
        "fallen_survivors", "average_kills_per_day",
    ],
    "eyebrow": "The race so far",
    "heading": "Rat Race by the numbers",
    "show_heading": False,
}

CTA_CARDS = (
    (
        "Enter the Rat Race",
        "Create your Rat Racer account and reserve the name the community will know you by.",
        "Sign Up",
        "/signup/#sign-up",
    ),
    (
        "Check Your Mods",
        "Review the current rulings before adding a mod to your challenge game.",
        "View Allowed Mods",
        "/mods/",
    ),
    (
        "Follow the Competition",
        "Meet the active survivors and see who is leading the Rat Race.",
        "View Rankings",
        "/leaderboard/",
    ),
)


def compose_homepage(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    PageBlock = apps.get_model("pages", "PageBlock")
    PageSection = apps.get_model("pages", "PageSection")
    SectionItem = apps.get_model("pages", "SectionItem")

    page = Page.objects.filter(slug="home").first()
    if not page:
        return

    existing_cards = PageBlock.objects.filter(
        section__page=page, block_type="card_group"
    ).order_by("section__position", "position").first()
    if existing_cards:
        existing_cards.block_type = "cta_cards"
        existing_cards.content = "Choose your next move"
        existing_cards.card_columns = "3"
        existing_cards.save(update_fields=("block_type", "content", "card_columns"))
        existing_cards.items.all().delete()
        for position, (heading, description, button_label, destination_url) in enumerate(CTA_CARDS):
            SectionItem.objects.create(
                block=existing_cards,
                position=position * 10,
                heading=heading,
                description=description,
                button_label=button_label,
                destination_url=destination_url,
            )

    ranking = PageBlock.objects.filter(
        section__page=page, block_type="ranking_table"
    ).order_by("section__position", "position").first()
    if ranking:
        section = ranking.section
        section.name = "Community statistics"
        section.width = "full"
        section.layout = "single"
        section.background = "alternate"
        section.full_bleed_background = True
        section.save(update_fields=(
            "name", "width", "layout", "background", "full_bleed_background",
        ))
        ranking.block_type = "community_stats"
        ranking.content = ""
        ranking.community_stats_config = STATS_CONFIG
        ranking.save(update_fields=(
            "block_type", "content", "community_stats_config",
        ))
    elif not PageBlock.objects.filter(
        section__page=page, block_type="community_stats"
    ).exists():
        section = PageSection.objects.create(
            page=page,
            position=20,
            name="Community statistics",
            is_visible=True,
            width="full",
            layout="single",
            background="alternate",
            full_bleed_background=True,
        )
        PageBlock.objects.create(
            section=section,
            position=0,
            column=0,
            is_visible=True,
            block_type="community_stats",
            community_stats_config=STATS_CONFIG,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_create_legacy_hall_of_fame_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='community_stats_config',
            field=models.JSONField(blank=True, default=dict, help_text='Validated selection and ordering of verified community metrics.', verbose_name='community statistics configuration'),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='destination_url',
            field=models.CharField(blank=True, help_text='A site-relative path, page anchor, or secure web address.', max_length=500),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('action', 'Button or link'), ('card_group', 'Card group'), ('cta_cards', 'Call-to-action cards'), ('community_stats', 'Community statistics'), ('image', 'Image'), ('gallery', 'Gallery'), ('ranking_table', 'Ranking table')], max_length=24),
        ),
        migrations.RunPython(compose_homepage, migrations.RunPython.noop),
    ]
