# Generated by Django 5.2.16 on 2026-08-06 00:30

from django.db import migrations, models


def apply_to_homepage_statistics(apps, schema_editor):
    PageSection = apps.get_model("pages", "PageSection")
    PageSection.objects.filter(
        page__slug="home",
        blocks__block_type="community_stats",
    ).update(
        background="alternate_full",
        full_bleed_background=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_community_stats_and_cta_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='background',
            field=models.CharField(choices=[('default', 'Page background'), ('surface', 'Raised surface'), ('alternate', 'Alternate surface'), ('alternate_full', 'Alternate surface - full width')], default='default', max_length=16),
        ),
        migrations.RunPython(
            apply_to_homepage_statistics,
            migrations.RunPython.noop,
        ),
    ]
