# Generated by Django 5.2.16 on 2026-08-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_cta_cards_as_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='cta_show_numbers',
            field=models.BooleanField(default=True, help_text="Display the card's ordered number above its heading.", verbose_name='show card number'),
        ),
    ]
