# Generated by Django 5.2.16 on 2026-08-06 00:57

from django.db import migrations, models


def preserve_existing_card_numbers(apps, schema_editor):
    PageBlock = apps.get_model("pages", "PageBlock")
    for block in PageBlock.objects.filter(block_type__in=("card_group", "cta_cards")):
        if block.block_type == "cta_cards" and not block.cta_show_numbers:
            continue
        for number, item in enumerate(block.items.order_by("position", "pk"), start=1):
            item.card_label = f"{number:02d}" if block.block_type == "cta_cards" else str(number)
            item.save(update_fields=("card_label",))


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_cta_card_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='audience',
            field=models.CharField(choices=[('inherit', 'Inherit from card group'), ('everyone', 'Everyone'), ('visitors', 'Signed-out visitors'), ('signed_in', 'Signed-in participants'), ('hidden', 'Hidden')], default='inherit', max_length=16),
        ),
        migrations.AddField(
            model_name='sectionitem',
            name='card_label',
            field=models.CharField(blank=True, help_text='Optional text displayed above the card heading, such as 01 or Start.', max_length=16, verbose_name='number or label'),
        ),
        migrations.RunPython(preserve_existing_card_numbers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pageblock',
            name='cta_show_numbers',
        ),
    ]
