# Generated by Django 5.2.16 on 2026-08-06 01:09

from django.db import migrations, models


def merge_card_group_types(apps, schema_editor):
    PageBlock = apps.get_model("pages", "PageBlock")
    PageBlock.objects.filter(block_type="cta_cards").update(
        block_type="card_group",
        card_style="linked",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_remove_pageblock_cta_show_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='card_style',
            field=models.CharField(choices=[('standard', 'Standard cards'), ('linked', 'Linked action cards')], default='standard', max_length=12),
        ),
        migrations.RunPython(merge_card_group_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('action', 'Button or link'), ('card_group', 'Card group'), ('community_stats', 'Community statistics'), ('image', 'Image'), ('gallery', 'Gallery'), ('ranking_table', 'Ranking table')], max_length=24),
        ),
    ]
