# Generated by Django 5.2.16 on 2026-08-06 01:18

from django.db import migrations, models


def move_style_to_cards(apps, schema_editor):
    PageBlock = apps.get_model("pages", "PageBlock")
    for block in PageBlock.objects.filter(block_type="card_group", card_style="linked"):
        block.items.update(card_type="linked")


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_pageblock_card_style_alter_pageblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='card_type',
            field=models.CharField(choices=[('standard', 'Standard card'), ('linked', 'Linked action card')], default='standard', max_length=12),
        ),
        migrations.RunPython(move_style_to_cards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pageblock',
            name='card_style',
        ),
    ]
