# Generated by Django 5.2.16 on 2026-08-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_bound_raised_surfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='separator_spacing',
            field=models.CharField(choices=[('small', 'Small'), ('standard', 'Standard'), ('large', 'Large')], default='standard', max_length=12),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='separator_style',
            field=models.CharField(choices=[('space', 'Space only'), ('line', 'Subtle line'), ('accent', 'Accent line')], default='space', max_length=12),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('action', 'Button or link'), ('card_group', 'Card group'), ('separator', 'Separator'), ('community_stats', 'Community statistics'), ('image', 'Image'), ('gallery', 'Gallery'), ('ranking_table', 'Ranking table')], max_length=24),
        ),
    ]
