# Generated by Django 5.2.16 on 2026-08-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_pageblock_separator_spacing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='separator_spacing',
            field=models.CharField(choices=[('very_small', 'Very small'), ('small', 'Small'), ('standard', 'Standard'), ('large', 'Large')], default='standard', max_length=12),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='separator_spacing',
            field=models.CharField(choices=[('very_small', 'Very small'), ('small', 'Small'), ('standard', 'Standard'), ('large', 'Large')], default='standard', max_length=16),
        ),
    ]
