"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e1_m0ype1#@%bpq1xhi$uq*lm66oj5v^3exvp+1q-1z6amm=+v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]"
    ).split(",")
    if host.strip()
]

# Public operator identity. These values are not secrets, but production may
# override them without changing source code or participant data.
SITE_LEGAL_NAME = os.environ.get("SITE_LEGAL_NAME", "Sentinel Tech Ltd")
SITE_COMPANY_NUMBER = os.environ.get("SITE_COMPANY_NUMBER", "10998950")
SITE_REGISTERED_OFFICE = os.environ.get(
    "SITE_REGISTERED_OFFICE",
    "Suite 15 The Enterprise Centre, Coxbridge Business Park, Farnham, Surrey, England, GU10 5EH",
)
SITE_PRIVACY_EMAIL = os.environ.get(
    "SITE_PRIVACY_EMAIL", "support@tgsrr.com"
)
PRIVACY_NOTICE_VERSION = "2026-08-14"
SITE_PUBLIC_URL = os.environ.get("SITE_PUBLIC_URL", "http://127.0.0.1:8000")
SITE_MAINTENANCE_MODE = os.environ.get(
    "SITE_MAINTENANCE_MODE", "false"
).strip().lower() in {"1", "true", "yes", "on"}
SITE_FULL_TITLE = os.environ.get(
    "SITE_FULL_TITLE", "The Great Spiffo's Rat Race"
)
SITE_SHORT_TITLE = os.environ.get("SITE_SHORT_TITLE", "The Rat Race")
SITE_TAGLINE = os.environ.get(
    "SITE_TAGLINE", "The official Rat Race challenge"
)
SITE_WELCOME_MESSAGE = os.environ.get(
    "SITE_WELCOME_MESSAGE", "Welcome to the Rat Race!"
)
SITE_HOMEPAGE_SMALL_HEADING = os.environ.get(
    "SITE_HOMEPAGE_SMALL_HEADING", "Welcome to The Rat Race"
)
SITE_HOMEPAGE_MAIN_HEADING = os.environ.get(
    "SITE_HOMEPAGE_MAIN_HEADING",
    "A survival challenge measured in stories, statistics and stubbornness.",
)
SITE_HOMEPAGE_INTRODUCTION = os.environ.get(
    "SITE_HOMEPAGE_INTRODUCTION",
    "The Great Spiffo's Rat Race is a long-form Project Zomboid challenge. "
    "Create your participant account now and you will be ready when the live "
    "challenge platform opens.",
)
SITE_HOMEPAGE_PRIMARY_BUTTON = os.environ.get(
    "SITE_HOMEPAGE_PRIMARY_BUTTON", "Join The Rat Race"
)
SITE_HOMEPAGE_SECONDARY_LINK = os.environ.get(
    "SITE_HOMEPAGE_SECONDARY_LINK", "I already have an account"
)
SITE_HOMEPAGE_ACCOUNT_BUTTON = os.environ.get(
    "SITE_HOMEPAGE_ACCOUNT_BUTTON", "Go to your account"
)
SITE_SIGN_IN_PROMPT = os.environ.get("SITE_SIGN_IN_PROMPT", "Existing Racer?")
SITE_JOIN_STEP_1_HEADING = os.environ.get(
    "SITE_JOIN_STEP_1_HEADING", "Reserve your name"
)
SITE_JOIN_STEP_1_DESCRIPTION = os.environ.get(
    "SITE_JOIN_STEP_1_DESCRIPTION",
    "Choose the nickname other Rat Racers will know you by.",
)
SITE_JOIN_STEP_2_HEADING = os.environ.get(
    "SITE_JOIN_STEP_2_HEADING", "Verify your email"
)
SITE_JOIN_STEP_2_DESCRIPTION = os.environ.get(
    "SITE_JOIN_STEP_2_DESCRIPTION",
    "Confirm the address used to secure your participant account.",
)
SITE_JOIN_STEP_3_HEADING = os.environ.get(
    "SITE_JOIN_STEP_3_HEADING", "Get race-ready"
)
SITE_JOIN_STEP_3_DESCRIPTION = os.environ.get(
    "SITE_JOIN_STEP_3_DESCRIPTION",
    "Your account will be waiting for run updates when mod integration opens.",
)
SITE_PARTICIPANT_LABEL = os.environ.get("SITE_PARTICIPANT_LABEL", "Rat Racer")
SITE_PARTICIPANT_PLURAL_LABEL = os.environ.get(
    "SITE_PARTICIPANT_PLURAL_LABEL", "Rat Racers"
)
SITE_FORMER_PARTICIPANT_LABEL = os.environ.get(
    "SITE_FORMER_PARTICIPANT_LABEL", "Former Rat Racer"
)
SITE_RUN_UPDATE_LABEL = os.environ.get("SITE_RUN_UPDATE_LABEL", "Run update")
SITE_RUN_UPDATE_PLURAL_LABEL = os.environ.get(
    "SITE_RUN_UPDATE_PLURAL_LABEL", "Run updates"
)
SITE_DISCLAIMER = os.environ.get(
    "SITE_DISCLAIMER", "Not affiliated with or endorsed by The Indie Stone."
)
SITE_ATTRIBUTION_TEXT = os.environ.get(
    "SITE_ATTRIBUTION_TEXT",
    "Thanks to The Indie Stone for creating Project Zomboid, which made this "
    "possible. This is an unofficial fan production for non-commercial purposes "
    "made under the",
)
SITE_ATTRIBUTION_URL = os.environ.get(
    "SITE_ATTRIBUTION_URL", "https://store.steampowered.com/eula/108600_eula_1"
)


# Application definition

INSTALLED_APPS = [
    'registry.admin_site.RatRaceAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'administration',
    'branding',
    'pages',
    'registry',
    'zomboid_catalogue',
    'operations',
]

AUTH_USER_MODEL = 'registry.Participant'
LOGIN_URL = 'registry:login'
LOGIN_REDIRECT_URL = 'registry:account'
LOGOUT_REDIRECT_URL = 'registry:home'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'config.middleware.MaintenanceModeMiddleware',
    'config.middleware.DevelopmentNoStoreMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.site_identity',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
AVATAR_QUARANTINE_ROOT = BASE_DIR / 'private_uploads' / 'avatars'
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODERATION_URL = "https://api.openai.com/v1/moderations"
AVATAR_UPLOAD_MAX_BYTES = 5 * 1024 * 1024

# Streaming-provider credentials are optional in development. Connections are
# only enabled when all provider credentials and a separate Fernet encryption
# key are supplied.
STREAMING_TOKEN_ENCRYPTION_KEY = os.environ.get(
    "STREAMING_TOKEN_ENCRYPTION_KEY", ""
)
TWITCH_CLIENT_ID = os.environ.get("TWITCH_CLIENT_ID", "")
TWITCH_CLIENT_SECRET = os.environ.get("TWITCH_CLIENT_SECRET", "")
TWITCH_REDIRECT_URI = os.environ.get("TWITCH_REDIRECT_URI", "")
TWITCH_HTTP_TIMEOUT_SECONDS = 10
DISCORD_CLIENT_ID = os.environ.get("DISCORD_CLIENT_ID", "")
DISCORD_CLIENT_SECRET = os.environ.get("DISCORD_CLIENT_SECRET", "")
DISCORD_REDIRECT_URI = os.environ.get("DISCORD_REDIRECT_URI", "")
DISCORD_HTTP_TIMEOUT_SECONDS = 10
YOUTUBE_CLIENT_ID = os.environ.get("YOUTUBE_CLIENT_ID", "")
YOUTUBE_CLIENT_SECRET = os.environ.get("YOUTUBE_CLIENT_SECRET", "")
YOUTUBE_REDIRECT_URI = os.environ.get("YOUTUBE_REDIRECT_URI", "")
YOUTUBE_HTTP_TIMEOUT_SECONDS = 10

# Local development prints verification emails to the server console. Production
# will override this with the Microsoft 365 email backend/configuration.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = f"{SITE_FULL_TITLE} <no-reply@localhost>"
VERIFICATION_LINK_MAX_AGE = 60 * 60 * 24
PENDING_REGISTRATION_MAX_AGE = 60 * 60 * 24 * 7
PARTICIPANT_MINIMUM_AGE = 18
AGE_ELIGIBILITY_POLICY_VERSION = "18-plus-v1"

# Cloudflare's published test credentials make the complete Turnstile flow work
# on localhost. Production must provide real credentials through environment
# variables; the test credentials must never be used on the live website.
TURNSTILE_SITE_KEY = os.environ.get(
    "TURNSTILE_SITE_KEY", "1x00000000000000000000AA"
)
TURNSTILE_SECRET_KEY = os.environ.get(
    "TURNSTILE_SECRET_KEY", "1x0000000000000000000000000000000AA"
)
TURNSTILE_VERIFY_URL = (
    "https://challenges.cloudflare.com/turnstile/v0/siteverify"
)
TURNSTILE_TIMEOUT_SECONDS = 5

# Fixed-window limits use the selected shared production runtime-state backend.
SIGNUP_RATE_LIMIT = 5
SIGNUP_RATE_WINDOW_SECONDS = 60 * 60
RESEND_IP_RATE_LIMIT = 5
RESEND_EMAIL_RATE_LIMIT = 3
RESEND_RATE_WINDOW_SECONDS = 60 * 60
PASSWORD_RESET_IP_RATE_LIMIT = 5
PASSWORD_RESET_EMAIL_RATE_LIMIT = 3
PASSWORD_RESET_RATE_WINDOW_SECONDS = 60 * 60
PASSWORD_RESET_TIMEOUT = 60 * 60
TRUST_CLOUDFLARE_CONNECTING_IP = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
RELEASE_ID = os.environ.get("RELEASE_ID", "development")
REFERENCE_WORKER_HEARTBEAT_INTERVAL_SECONDS = 15
REFERENCE_WORKER_HEARTBEAT_TTL_SECONDS = 60

# The full Project Zomboid reference installation is maintained by a scheduled,
# host-level command. Steam's cached session remains in SteamCMD's protected
# config directory and is never stored by Django.
STEAMCMD_EXECUTABLE = os.environ.get("STEAMCMD_EXECUTABLE", "")
STEAMCMD_USERNAME = os.environ.get("STEAMCMD_USERNAME", "")
STEAM_WEB_API_KEY = os.environ.get("STEAM_WEB_API_KEY", "")
PZ_REFERENCE_ROOT = os.environ.get("PZ_REFERENCE_ROOT", "")
STEAMCMD_UPDATE_TIMEOUT_SECONDS = int(
    os.environ.get("STEAMCMD_UPDATE_TIMEOUT_SECONDS", "1800")
)
STEAMCMD_AUTH_TIMEOUT_SECONDS = int(
    os.environ.get("STEAMCMD_AUTH_TIMEOUT_SECONDS", "15")
)
JAVA_EXECUTABLE = os.environ.get("JAVA_EXECUTABLE", "java")
VINEFLOWER_JAR = os.environ.get("VINEFLOWER_JAR", "")
PZ_DECOMPILATION_TIMEOUT_SECONDS = int(
    os.environ.get("PZ_DECOMPILATION_TIMEOUT_SECONDS", "3600")
)
