# Generated by Django 5.2.16 on 2026-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_website_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetheme',
            name='body_font',
            field=models.CharField(choices=[('system', 'Modern system'), ('humanist', 'Humanist'), ('mono', 'Technical monospace'), ('oswald', 'Oswald')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='websitetheme',
            name='heading_font',
            field=models.CharField(choices=[('system', 'Modern system'), ('condensed', 'Condensed poster'), ('slab', 'Slab serif'), ('oswald', 'Oswald'), ('derelict', 'Derelict'), ('derelict_rough', 'Derelict Rough')], default='system', max_length=20),
        ),
    ]
