# Generated by Django 5.2.16 on 2026-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_alter_websitetheme_body_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetheme',
            name='body_font_weight',
            field=models.CharField(choices=[('200', 'ExtraLight (200)'), ('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'SemiBold (600)'), ('700', 'Bold (700)')], default='400', max_length=3),
        ),
        migrations.AddField(
            model_name='websitetheme',
            name='heading_font_weight',
            field=models.CharField(choices=[('200', 'ExtraLight (200)'), ('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'SemiBold (600)'), ('700', 'Bold (700)')], default='700', max_length=3),
        ),
    ]
