# Generated by Django 5.2.16 on 2026-07-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_websitetheme_body_font_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetheme',
            name='body_font_spacing',
            field=models.CharField(choices=[('tight', 'Tight'), ('normal', 'Normal'), ('relaxed', 'Relaxed'), ('wide', 'Wide')], default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='websitetheme',
            name='heading_font_spacing',
            field=models.CharField(choices=[('tight', 'Tight'), ('normal', 'Normal'), ('relaxed', 'Relaxed'), ('wide', 'Wide')], default='normal', max_length=8),
        ),
    ]
