# Generated by Django 5.2.16 on 2026-07-15 15:45

from django.db import migrations, models


def preserve_existing_heading_as_display(apps, schema_editor):
    WebsiteTheme = apps.get_model("branding", "WebsiteTheme")
    for theme in WebsiteTheme.objects.all():
        theme.display_font = theme.heading_font
        theme.display_font_weight = theme.heading_font_weight
        theme.display_font_spacing = theme.heading_font_spacing
        theme.save(
            update_fields=(
                "display_font",
                "display_font_weight",
                "display_font_spacing",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_websitetheme_body_font_spacing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetheme',
            name='display_font',
            field=models.CharField(choices=[('system', 'Modern system'), ('condensed', 'Condensed poster'), ('slab', 'Slab serif'), ('oswald', 'Oswald'), ('derelict', 'Derelict'), ('derelict_rough', 'Derelict Rough')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='websitetheme',
            name='display_font_spacing',
            field=models.CharField(choices=[('tight', 'Tight'), ('normal', 'Normal'), ('relaxed', 'Relaxed'), ('wide', 'Wide')], default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='websitetheme',
            name='display_font_weight',
            field=models.CharField(choices=[('200', 'ExtraLight (200)'), ('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'SemiBold (600)'), ('700', 'Bold (700)')], default='700', max_length=3),
        ),
        migrations.RunPython(
            preserve_existing_heading_as_display,
            migrations.RunPython.noop,
        ),
    ]
