# Generated by Django 5.2.16 on 2026-07-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0006_websitetheme_display_font_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebranding',
            options={'verbose_name': 'branding', 'verbose_name_plural': 'branding'},
        ),
        migrations.AlterModelOptions(
            name='websitetheme',
            options={'ordering': ('name',), 'verbose_name': 'theme', 'verbose_name_plural': 'themes'},
        ),
    ]
