# Generated by Django 5.2.16 on 2026-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0007_alter_sitebranding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_account_button',
            field=models.CharField(default='Go to your account', max_length=80, verbose_name='signed-in account button text'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_introduction',
            field=models.TextField(default="The Great Spiffo's Rat Race is a long-form Project Zomboid challenge. Create your participant account now and you will be ready when the live challenge platform opens.", max_length=600, verbose_name='introduction text'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_main_heading',
            field=models.CharField(default='A survival challenge measured in stories, statistics and stubbornness.', max_length=240, verbose_name='main heading'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_primary_button',
            field=models.CharField(default='Join The Rat Race', max_length=80, verbose_name='primary button text'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_secondary_link',
            field=models.CharField(default='I already have an account', max_length=80, verbose_name='secondary link text'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_small_heading',
            field=models.CharField(default='Welcome to The Rat Race', max_length=160, verbose_name='small heading'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='join_step_1_description',
            field=models.CharField(default='Choose the nickname other Rat Racers will know you by.', max_length=240, verbose_name='step 1 description'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='join_step_1_heading',
            field=models.CharField(default='Reserve your name', max_length=100, verbose_name='step 1 heading'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='join_step_2_description',
            field=models.CharField(default='Confirm the address used to secure your participant account.', max_length=240, verbose_name='step 2 description'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='join_step_2_heading',
            field=models.CharField(default='Verify your email', max_length=100, verbose_name='step 2 heading'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='join_step_3_description',
            field=models.CharField(default='Your account will be waiting for run updates when mod integration opens.', max_length=240, verbose_name='step 3 description'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='join_step_3_heading',
            field=models.CharField(default='Get race-ready', max_length=100, verbose_name='step 3 heading'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='participant_label',
            field=models.CharField(default='Rat Racer', max_length=60, verbose_name='participant name'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='participant_plural_label',
            field=models.CharField(default='Rat Racers', max_length=60, verbose_name='participant plural'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='run_update_label',
            field=models.CharField(default='Run update', max_length=60, verbose_name='run update name'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='run_update_plural_label',
            field=models.CharField(default='Run updates', max_length=60, verbose_name='run update plural'),
        ),
    ]
