# Generated by Django 5.2.16 on 2026-07-18 15:01

import branding.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0008_sitebranding_homepage_account_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='attribution_new_tab',
            field=models.BooleanField(default=True, verbose_name='open attribution link in a new tab'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='attribution_text',
            field=models.TextField(default='Thanks to The Indie Stone for creating Project Zomboid, which made this possible. This is an unofficial fan production for non-commercial purposes made under the', max_length=600),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='attribution_url',
            field=models.URLField(default='https://store.steampowered.com/eula/108600_eula_1'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Decorative only. The active theme colour remains as a fallback.', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size]),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='enable_background_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='enable_favicon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='enable_header_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='enable_homepage_feature_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='enable_social_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='favicon',
            field=models.ImageField(blank=True, help_text='A square PNG or ICO works best.', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size]),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='header_logo',
            field=models.ImageField(blank=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size]),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='header_logo_alt',
            field=models.CharField(blank=True, help_text='Describe the logo for people who cannot see it.', max_length=160, verbose_name='header logo alternative text'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_feature_image',
            field=models.ImageField(blank=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size]),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_feature_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='homepage feature image alternative text'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='show_attribution',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='social_image',
            field=models.ImageField(blank=True, help_text='Used when the website is shared on services such as Discord.', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size], verbose_name='social sharing image'),
        ),
    ]
