# Generated by Django 5.2.16 on 2026-07-18 15:53

import branding.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0009_sitebranding_attribution_new_tab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(upload_to='branding/library/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size, branding.models.validate_brand_image_content])),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Decorative only. The active theme colour remains as a fallback.', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size, branding.models.validate_brand_image_content]),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='favicon',
            field=models.ImageField(blank=True, help_text='A square PNG or ICO works best.', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size, branding.models.validate_brand_image_content]),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='header_logo',
            field=models.ImageField(blank=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size, branding.models.validate_brand_image_content]),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='homepage_feature_image',
            field=models.ImageField(blank=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size, branding.models.validate_brand_image_content]),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='social_image',
            field=models.ImageField(blank=True, help_text='Used when the website is shared on services such as Discord.', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg', 'webp', 'ico')), branding.models.validate_brand_image_size, branding.models.validate_brand_image_content], verbose_name='social sharing image'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_image_branding', to='branding.managedimage', verbose_name='background image'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='favicon_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favicon_branding', to='branding.managedimage', verbose_name='favicon image'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='header_logo_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='header_logo_branding', to='branding.managedimage', verbose_name='header logo image'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_feature_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_feature_branding', to='branding.managedimage', verbose_name='homepage feature image'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='social_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='social_image_branding', to='branding.managedimage', verbose_name='social sharing image'),
        ),
    ]
