# Generated by Django 5.2.16 on 2026-07-18 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0011_managedimage_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_brightness',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(200)], verbose_name='brightness'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_contrast',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(200)], verbose_name='contrast'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_fixed',
            field=models.BooleanField(default=True, verbose_name='keep background fixed while scrolling'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_opacity',
            field=models.PositiveSmallIntegerField(default=100, help_text='0% hides the image and 100% shows it fully.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='image opacity'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_position',
            field=models.CharField(choices=[('left top', 'Top left'), ('center top', 'Top centre'), ('right top', 'Top right'), ('left center', 'Centre left'), ('center center', 'Centre'), ('right center', 'Centre right'), ('left bottom', 'Bottom left'), ('center bottom', 'Bottom centre'), ('right bottom', 'Bottom right')], default='center top', max_length=20, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_saturation',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='saturation'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_image_scale',
            field=models.CharField(choices=[('cover', 'Fill screen'), ('contain', 'Fit whole image'), ('auto', 'Original size'), ('repeat', 'Tile image')], default='cover', max_length=12, verbose_name='scale'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='background_overlay_strength',
            field=models.PositiveSmallIntegerField(default=28, help_text='Adds the theme background colour over the image to keep text readable.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='theme overlay'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_feature_custom_height',
            field=models.PositiveSmallIntegerField(default=24, help_text='Used only when height is set to Custom height.', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(60)], verbose_name='custom height (rem)'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_feature_fit',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Show whole image')], default='cover', max_length=12, verbose_name='image fit'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_feature_height',
            field=models.CharField(choices=[('standard', 'Standard - maximum 24rem'), ('natural', 'Natural proportions'), ('short', 'Short banner - 12rem'), ('tall', 'Tall banner - 32rem'), ('custom', 'Custom height')], default='standard', max_length=12, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='homepage_feature_position',
            field=models.CharField(choices=[('left top', 'Top left'), ('center top', 'Top centre'), ('right top', 'Top right'), ('left center', 'Centre left'), ('center center', 'Centre'), ('right center', 'Centre right'), ('left bottom', 'Bottom left'), ('center bottom', 'Bottom centre'), ('right bottom', 'Bottom right')], default='center center', max_length=20, verbose_name='focal position'),
        ),
    ]
