# Generated by Django 5.2.16 on 2026-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0012_sitebranding_background_image_brightness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='sign_in_prompt',
            field=models.CharField(default='Existing Racer?', help_text='Short text shown before Sign In in the public navigation.', max_length=80, verbose_name='sign-in prompt'),
        ),
    ]
