# Generated by Django 5.2.16 on 2026-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_reference_update_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesource',
            name='decompiled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='referencesource',
            name='decompiled_build_id',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='referencesource',
            name='decompiled_root',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='referencesource',
            name='decompiler_jar',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='referencesource',
            name='java_executable',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='referenceupdatejob',
            name='operation',
            field=models.CharField(choices=[('update', 'Steam update'), ('decompile', 'Decompile')], default='update', max_length=16),
        ),
    ]
