# Generated by Django 5.2.16 on 2026-07-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_artwork_jobs(apps, schema_editor):
    Review = apps.get_model("operations", "CatalogueImportReview")
    Job = apps.get_model("operations", "PZWikiArtworkSyncJob")
    for review in Review.objects.exclude(wiki_icon_status="not_requested"):
        status = review.wiki_icon_status
        summary = review.wiki_icon_summary
        started_at = review.reviewed_at if status == "running" else None
        finished_at = review.reviewed_at if status in ("complete", "failed") else None
        if status == "running":
            status = "queued"
            started_at = None
            summary = (
                "Queued to resume after PZWiki artwork jobs were separated from "
                "catalogue reviews."
            )
        trigger = "manual" if "manually" in summary.lower() else "catalogue_approval"
        job = Job.objects.create(
            source_id=review.source_id,
            catalogue_review_id=review.pk,
            status=status,
            trigger=trigger,
            requested_by_id=review.reviewed_by_id or review.requested_by_id,
            started_at=started_at,
            finished_at=finished_at,
            summary=summary,
        )
        Job.objects.filter(pk=job.pk).update(
            requested_at=review.reviewed_at or review.requested_at
        )


def restore_review_artwork_state(apps, schema_editor):
    Review = apps.get_model("operations", "CatalogueImportReview")
    Job = apps.get_model("operations", "PZWikiArtworkSyncJob")
    for review in Review.objects.all():
        job = Job.objects.filter(catalogue_review_id=review.pk).order_by(
            "-requested_at", "-pk"
        ).first()
        if job:
            status = "not_requested" if job.status == "cancelled" else job.status
            Review.objects.filter(pk=review.pk).update(
                wiki_icon_status=status,
                wiki_icon_summary=job.summary,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_catalogueimportreview_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PZWikiArtworkSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('trigger', models.CharField(choices=[('catalogue_approval', 'Catalogue approval'), ('manual', 'Manual')], max_length=24)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('catalogue_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pzwiki_artwork_jobs', to='operations.catalogueimportreview')),
                ('requested_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pzwiki_artwork_jobs', to='operations.referencesource')),
            ],
            options={
                'verbose_name': 'PZWiki artwork sync job',
                'verbose_name_plural': 'PZWiki artwork sync jobs',
                'ordering': ('-requested_at', '-pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('catalogue_review',), name='operations_one_active_pzwiki_job_per_review')],
            },
        ),
        migrations.RunPython(
            preserve_artwork_jobs,
            restore_review_artwork_state,
        ),
        migrations.RemoveField(
            model_name='catalogueimportreview',
            name='wiki_icon_status',
        ),
        migrations.RemoveField(
            model_name='catalogueimportreview',
            name='wiki_icon_summary',
        ),
    ]
