# Generated by Django 5.2.16 on 2026-07-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_remove_catalogueimportreview_wiki_icon_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunDataDangerZone',
            fields=[
            ],
            options={
                'verbose_name': 'run data danger zone',
                'verbose_name_plural': 'run data danger zone',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('operations.referencesource',),
        ),
    ]
