# Generated by Django 5.2.16 on 2026-07-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_rundatadangerzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzwikiartworksyncjob',
            name='unavailable_artwork',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
