# Generated by Django 5.2.17 on 2026-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_ratelimitbucket_workerheartbeatrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceupdatejob',
            name='log_output',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='referenceupdatejob',
            name='progress_message',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='referenceupdatejob',
            name='progress_percent',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
