# Generated by Django 5.2.17 on 2026-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_referenceupdatejob_log_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceupdatejob',
            name='steam_branch',
            field=models.CharField(choices=[('public', 'Stable'), ('unstable', 'Unstable')], default='public', editable=False, max_length=16),
        ),
    ]
