THEME_PRESETS = {
    "survival-event": {
        "name": "Survival Event",
        "colour_scheme": "dark",
        "background_style": "radial",
        "heading_font": "condensed",
        "body_font": "system",
        "corner_style": "rounded",
        "shadow_style": "dramatic",
        "background_colour": "#151912",
        "background_highlight_colour": "#394628",
        "surface_colour": "#191F15",
        "surface_alt_colour": "#0F130D",
        "text_colour": "#F6F2DF",
        "muted_text_colour": "#C8CDBD",
        "accent_colour": "#F2A33A",
        "accent_hover_colour": "#F4AD53",
        "accent_text_colour": "#17120A",
        "border_colour": "#586746",
        "success_colour": "#A6D66D",
        "error_colour": "#FF9B91",
    },
    "retro-road-race": {
        "name": "Retro Road Race",
        "colour_scheme": "light",
        "background_style": "road",
        "heading_font": "slab",
        "body_font": "humanist",
        "corner_style": "subtle",
        "shadow_style": "soft",
        "background_colour": "#E4C991",
        "background_highlight_colour": "#A8442A",
        "surface_colour": "#FFF3D6",
        "surface_alt_colour": "#F0D9A9",
        "text_colour": "#2A1B16",
        "muted_text_colour": "#6F5548",
        "accent_colour": "#B53624",
        "accent_hover_colour": "#D1492E",
        "accent_text_colour": "#FFF8E8",
        "border_colour": "#805E45",
        "success_colour": "#39734A",
        "error_colour": "#A52323",
    },
    "clean-competition": {
        "name": "Clean Competition",
        "colour_scheme": "dark",
        "background_style": "flat",
        "heading_font": "system",
        "body_font": "system",
        "corner_style": "subtle",
        "shadow_style": "soft",
        "background_colour": "#0B1220",
        "background_highlight_colour": "#17233A",
        "surface_colour": "#111C2E",
        "surface_alt_colour": "#09101D",
        "text_colour": "#F5F7FB",
        "muted_text_colour": "#AEB9CC",
        "accent_colour": "#4DA3FF",
        "accent_hover_colour": "#78BAFF",
        "accent_text_colour": "#07111F",
        "border_colour": "#31425F",
        "success_colour": "#63D39A",
        "error_colour": "#FF8585",
    },
}
